version: '3.0'

services:
  rasa_chatbot:
    build: .
    image: rasa-chatbot:latest
    ports:
      - 5005:5005
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    command:
      - python3
      - -m
      - rasa_core.run
      - --enable_api
      - --core
      - /app/models/rasa_core
      - -u
      - /app/models/rasa_nlu/current/nlu
      - --endpoints
      - /app/config/endpoints.local.yml
    stdin_open: true
    tty: true

  action_server:
    build: actions
    image: rasa-chatbot-actions:latest
    volumes:
      - ./actions:/app/actions
    command:
      - python
      - -m
      - rasa_core_sdk.endpoint
      - --actions
      - actions.actions

